server:
  port: 8000
spring:
  mvc:
    static-path-pattern=/static/**:
  datasource:
    url: jdbc:mysql://localhost:3306/WuGong
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
